#use_frameworks!

source 'https://github.com/CocoaPods/Specs.git';
source 'https://github.com/yangshiyu666/sRepo.git';



platform :ios, '8.0'

target 'OMTSocial_Example' do
  pod 'OMTSocial', :path => '../'

  target 'OMTSocial_Tests' do
    inherit! :search_paths

    
  end
end
